spring:
   application:
      name: currency-exchange
   cloud:
      config:
         import-check:
            enabled: false
   sleuth:
      sampler:
         probability: 1.0
   jpa:
      show-sql: true
   datasource:
      url: jdbc:h2:mem:testdb
   h2:
      console:
         enabled: true
server:
   port: 8000
eureka:
   instance:
      hostname: localhost
   client:
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:8761/eureka/
resilience4j.retry:
   configs:
      default:
         maxRetryAttempts: 5
         waitDuration: 100
         
         
         